#!/bin/bash

# MANUAL TEST SCRIPT FOR PATHFINDING
# Run this after importing the topology in the browser

echo "=================================="
echo "PATHFINDING MANUAL TEST GUIDE"
echo "=================================="
echo ""
echo "Topology File: netviz-pro-topology-2025-11-30T18_44_02.838Z.json"
echo "Expected Results: ALL paths should work"
echo ""
echo "STEP 1: Open browser to http://localhost:9080"
echo "STEP 2: Login with your credentials"
echo "STEP 3: Click IMPORT button"
echo "STEP 4: Select file: zzzi--input-files/netviz-pro-topology-2025-11-30T18_44_02.838Z.json"
echo "STEP 5: Verify log shows: 'Imported: 10 nodes, 18 links'"
echo ""
echo "TEST CASES TO RUN:"
echo "=================================="
echo ""
echo "TEST 1: Direct Connection (1 hop)"
echo "  Source: zwe-bul-pop-p04"
echo "  Destination: zwe-bul-pop-p03"
echo "  Expected: ✅ Path found (1 hop)"
echo "  Status: USER CONFIRMED WORKING ✅"
echo ""
echo "TEST 2: Two-Hop Path"
echo "  Source: zwe-bul-pop-p04"
echo "  Destination: deu-ber-bes-pe10"
echo "  Expected: ✅ Path found (2 hops)"
echo "  Expected Route: zwe-bul-pop-p04 → deu-ber-bes-p06 → deu-ber-bes-pe10"
echo ""
echo "TEST 3: Cross-Country Path"
echo "  Source: gbr-ldn-wst-pe09"
echo "  Destination: deu-ber-bes-pe10"
echo "  Expected: ✅ Path found (2 hops)"
echo "  Expected Route: gbr-ldn-wst-pe09 → deu-ber-bes-p06 → deu-ber-bes-pe10"
echo ""
echo "TEST 4: Three-Hop Path"
echo "  Source: usa-nyc-dc1-rr08"
echo "  Destination: zwe-hra-pop-p02"
echo "  Expected: ✅ Path found (3 hops)"
echo "  Expected Route: usa-nyc-dc1-rr08 → zwe-bul-pop-p04 → zwe-hra-pop-p01 → zwe-hra-pop-p02"
echo ""
echo "TEST 5: Another Two-Hop"
echo "  Source: gbr-ldn-wst-pe09"
echo "  Destination: gbr-ldn-wst-p07"
echo "  Expected: ✅ Path found (1 hop - reverse edge)"
echo "  Expected Route: gbr-ldn-wst-pe09 → gbr-ldn-wst-p07"
echo ""
echo "=================================="
echo "TROUBLESHOOTING:"
echo "=================================="
echo ""
echo "If you see 'No path found':"
echo "1. Open browser console (F12)"
echo "2. Look for these debug messages:"
echo "   - 'Effective edges count: 36' (should be 36, not less)"
echo "   - 'Sample edges:' (should show edges with from/to/cost)"
echo ""
echo "3. Check the logs panel:"
echo "   - Should show node names (not 'undefined')"
echo "   - Example: 'Finding path: gbr-ldn-wst-pe09 -> deu-ber-bes-pe10...'"
echo ""
echo "4. Verify topology is imported:"
echo "   - Dropdowns should show 10 routers"
echo "   - Graph should show 10 colored nodes"
echo "   - Log should say 'Imported: 10 nodes, 18 links'"
echo ""
echo "5. Hard refresh if needed:"
echo "   - Mac: Cmd+Shift+R"
echo "   - Windows/Linux: Ctrl+Shift+R"
echo ""
echo "=================================="






